"""
sta_server.py
MCP Tool — runs OpenSTA static timing analysis via TCL scripts.
For V2 RTL-to-GDS framework.

Pattern: mcp.server.Server with @server.tool() decorator, runs via stdio.
"""

import asyncio
import subprocess
import re
from pathlib import Path
from v1_core.utils import logger

try:
    from mcp.server import Server
    from mcp.server.stdio import stdio_server
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False

WORKSPACE = Path("workspace").resolve()


def _generate_tcl_script(
    netlist_file: str,
    liberty_file: str,
    top_module: str,
    clock_period_ns: float,
    sta_dir: Path,
) -> Path:
    """Generate an OpenSTA TCL script and return its path."""
    tcl_path = sta_dir / "sta.tcl"

    netlist_abs = str(Path(netlist_file).resolve())
    liberty_abs = str(Path(liberty_file).resolve())

    tcl_content = f"""# OpenSTA timing analysis script
# Generated by sta_server.py — V2 RTL-to-GDS framework

# Read Liberty timing library
read_liberty {liberty_abs}

# Read synthesized Verilog netlist
read_verilog {netlist_abs}

# Link the top-level design
link_design {top_module}

# Create clock (assumes clock port is named "clk")
create_clock -name clk -period {clock_period_ns} [get_ports clk]

# Report timing results to files for parsing
report_checks -path_delay max -digits 3 > {sta_dir}/timing.rpt
report_wns -digits 3 > {sta_dir}/wns.rpt
report_tns -digits 3 > {sta_dir}/tns.rpt

exit
"""
    tcl_path.write_text(tcl_content.strip())
    logger.info(f"STA TCL script written to {tcl_path}")
    return tcl_path


def _parse_sta_output(sta_dir: Path, raw_log: str) -> dict:
    """
    Parse OpenSTA output files and return structured timing results.

    Returns:
        {wns, tns, timing_met, critical_path, log}
    """
    result: dict = {
        "wns": None,
        "tns": None,
        "timing_met": False,
        "critical_path": "",
        "log": "",
    }

    log_parts = []

    # --- Parse WNS report ---
    wns_path = sta_dir / "wns.rpt"
    if wns_path.exists():
        wns_text = wns_path.read_text()
        log_parts.append("--- WNS Report ---\n" + wns_text)

        # OpenSTA 3.1.0 format: "wns max 0.000" or "wns max -0.123"
        match = re.search(r"wns\s+\w+\s+([-+]?\d+\.?\d*)", wns_text)
        if match:
            result["wns"] = float(match.group(1))
            logger.info(f"Parsed WNS: {result['wns']}")

    # --- Parse TNS report ---
    tns_path = sta_dir / "tns.rpt"
    if tns_path.exists():
        tns_text = tns_path.read_text()
        log_parts.append("\n--- TNS Report ---\n" + tns_text)

        # OpenSTA 3.1.0 format: "tns max 0.000"
        match = re.search(r"tns\s+\w+\s+([-+]?\d+\.?\d*)", tns_text)
        if match:
            result["tns"] = float(match.group(1))
            logger.info(f"Parsed TNS: {result['tns']}")

    # --- Parse timing report for critical path ---
    timing_path = sta_dir / "timing.rpt"
    if timing_path.exists():
        timing_text = timing_path.read_text()
        log_parts.append("\n--- Timing Report ---\n" + timing_text)

        startpoint = None
        endpoint = None
        slack = None

        # report_checks format: "Startpoint: _10_"
        m_start = re.search(r"Startpoint:\s*(.+)", timing_text)
        m_end = re.search(r"Endpoint:\s*(.+)", timing_text)
        # report_checks format: "slack (MET)" with preceding slack value
        # Look for the last slack value before (MET) or (VIOLATED)
        m_slack = re.search(r"slack\s+\(([^)]+)\)", timing_text)
        if m_slack:
            # The line before has the actual slack value, get it from the table
            # Format includes: "          -0.519   data arrival time"
            # Right before "data required time" - "data arrival time" = slack
            # Better: look for the numeric value in the slack summary line
            slack_lines = re.findall(r"(-?\d+\.?\d*)\s+slack\s+\((?:MET|VIOLATED)\)", timing_text)
            if slack_lines:
                slack = float(slack_lines[0])
        else:
            # Fallback: try older format
            m_slack_old = re.search(r"slack\s+([-+]?\d+\.?\d*)", timing_text)
            if m_slack_old:
                slack = float(m_slack_old.group(1))

        if m_start:
            startpoint = m_start.group(1).strip()
        if m_end:
            endpoint = m_end.group(1).strip()

        path_parts = []
        if startpoint:
            path_parts.append(f"Startpoint: {startpoint}")
        if endpoint:
            path_parts.append(f"Endpoint: {endpoint}")
        if slack is not None:
            path_parts.append(f"Slack: {slack}")

        if path_parts:
            result["critical_path"] = " | ".join(path_parts)

        # If we parsed a slack value from the timing report, use it as WNS
        if slack is not None and result["wns"] is None:
            result["wns"] = slack

    # --- Determine timing closure ---
    if result["wns"] is not None:
        result["timing_met"] = result["wns"] >= 0

    result["log"] = "\n".join(log_parts)
    return result


def _run_sta(
    netlist_file: str,
    liberty_file: str,
    top_module: str,
    clock_period_ns: float,
) -> dict:
    """
    Run OpenSTA static timing analysis.

    Generates a TCL script, executes `sta <script>` via subprocess,
    and parses the output reports for WNS, TNS, and critical path.

    Args:
        netlist_file: Path to synthesized Verilog netlist.
        liberty_file: Path to Liberty timing library (.lib).
        top_module: Name of the top-level module.
        clock_period_ns: Target clock period in nanoseconds.

    Returns:
        dict with keys: wns, tns, timing_met, critical_path, log
    """
    sta_dir = WORKSPACE / "sta"
    sta_dir.mkdir(parents=True, exist_ok=True)

    # Generate TCL script
    _generate_tcl_script(
        netlist_file=netlist_file,
        liberty_file=liberty_file,
        top_module=top_module,
        clock_period_ns=clock_period_ns,
        sta_dir=sta_dir,
    )

    logger.info(
        f"Running OpenSTA: top='{top_module}', period={clock_period_ns}ns"
    )

    raw_log = ""
    try:
        result = subprocess.run(
            ["sta", "sta.tcl"],
            capture_output=True,
            text=True,
            cwd=str(sta_dir),
            timeout=120,  # prevent hung STA from blocking pipeline
        )
        raw_log = result.stdout + result.stderr

        if raw_log:
            logger.info(f"STA output (first 300 chars): {raw_log[:300]}")
        else:
            logger.warning("OpenSTA produced no output")

        if result.returncode != 0:
            logger.error(f"OpenSTA exited with code {result.returncode}")
            logger.warning(f"OpenSTA stderr: {result.stderr}")

    except FileNotFoundError:
        error_msg = (
            "OpenSTA ('sta' command) not found in PATH. "
            "Install OpenSTA or check your environment."
        )
        logger.error(error_msg)
        return {
            "wns": None,
            "tns": None,
            "timing_met": False,
            "critical_path": "",
            "log": error_msg,
        }
    except Exception as e:
        error_msg = f"Failed to run OpenSTA: {e}"
        logger.error(error_msg)
        return {
            "wns": None,
            "tns": None,
            "timing_met": False,
            "critical_path": "",
            "log": error_msg,
        }

    # Parse the output reports
    parsed = _parse_sta_output(sta_dir, raw_log)

    if parsed["wns"] is not None:
        logger.info(
            f"STA complete: WNS={parsed['wns']}, TNS={parsed['tns']}, "
            f"Timing Met={parsed['timing_met']}"
        )
    else:
        logger.warning("STA parsing did not extract WNS/TNS values.")

    return parsed


# ---------------------------------------------------------------------------
# MCP Server — wrapped for LangGraph / MCP bridge consumption
# ---------------------------------------------------------------------------

if MCP_AVAILABLE:

    server = Server("sta-server")


    @server.tool()
    async def sta_timing_analysis(
        netlist_file: str,
        liberty_file: str,
        top_module: str,
        clock_period_ns: float,
    ) -> dict:
        """
        Run OpenSTA static timing analysis on a synthesized netlist.

        This tool generates an OpenSTA TCL script, executes it, and parses the
        results for worst negative slack (WNS), total negative slack (TNS),
        and the critical path.

        Args:
            netlist_file: Path to the synthesized Verilog netlist file.
            liberty_file: Path to the Liberty timing library file (.lib).
            top_module: Name of the top-level module in the design.
            clock_period_ns: Target clock period in nanoseconds.

        Returns:
            A dictionary containing:
            - wns: Worst Negative Slack (float, or None if unavailable)
            - tns: Total Negative Slack (float, or None if unavailable)
            - timing_met: True if WNS >= 0 (bool)
            - critical_path: Human-readable critical path description (str)
            - log: Full STA output log for debugging (str)
        """
        logger.info(
            f"STA timing analysis requested: "
            f"top={top_module}, period={clock_period_ns}ns"
        )
        return _run_sta(
            netlist_file=netlist_file,
            liberty_file=liberty_file,
            top_module=top_module,
            clock_period_ns=clock_period_ns,
        )


    async def main():
        """Run the STA MCP server via stdio transport."""
        logger.info("Starting STA MCP server (stdio)")
        async with stdio_server() as (read_stream, write_stream):
            await server.run(read_stream, write_stream)


    if __name__ == "__main__":
        asyncio.run(main())

else:
    # Fallback: expose the plain function when the MCP SDK is not installed.
    logger.warning(
        "MCP Python SDK not installed. "
        "Install with: pip install mcp\n"
        "Falling back to non-MCP mode — use _run_sta() directly."
    )

    if __name__ == "__main__":
        logger.error(
            "Cannot start MCP server: mcp package is not installed.\n"
            "  pip install mcp\n"
            "Then run: python -m v2_verification.mcp_tools.sta_server"
        )
