"""
synthesis_server.py
MCP Tool — wraps Yosys synthesis via TCL scripts for V2 RTL-to-GDS framework.

Usage:
    python -m v2_verification.mcp_tools.synthesis_server

This creates an MCP stdio server that exposes a single tool: synthesize.
Connect via Claude Desktop or any MCP client.

Requirements:
    - mcp (Python SDK) >= 1.0
    - yosys installed and on PATH
"""

import asyncio
import re
import subprocess
from pathlib import Path
from typing import List

from v1_core.utils import logger

WORKSPACE = Path("workspace") / "synthesis"

# ---------------------------------------------------------------------------
# Core synthesis logic (non-async, called by the async MCP tool)
# ---------------------------------------------------------------------------


def _run_synthesis(
    rtl_file: str,
    top_module: str,
    liberty_file: str,
) -> dict:
    """Execute Yosys synthesis and return parsed results.

    This is deliberately a plain synchronous function so it can be unit-tested
    or called from other contexts without the MCP layer.
    """
    WORKSPACE.mkdir(parents=True, exist_ok=True)

    rtl_path = Path(rtl_file).resolve()
    lib_path = Path(liberty_file).resolve()

    if not rtl_path.exists():
        raise FileNotFoundError(f"RTL file not found: {rtl_path}")
    if not lib_path.exists():
        raise FileNotFoundError(f"Liberty file not found: {lib_path}")

    netlist_path = WORKSPACE / f"{top_module}_netlist.v"
    tcl_path = WORKSPACE / f"{top_module}_synthesis.tcl"

    # ---- Write Yosys TCL script ------------------------------------------
    tcl_content = f"""# Yosys synthesis script for {top_module}
# Auto-generated by synthesis_server.py

# Read the Verilog RTL
read_verilog {rtl_path}

# Synthesize to generic gates
synth -top {top_module}

# Map flip-flops to liberty cells
dfflibmap -liberty {lib_path}

# Technology mapping with ABC
abc -liberty {lib_path}

# Write synthesized netlist
write_verilog {netlist_path}

# Print statistics
stat -liberty {lib_path}
"""
    tcl_path.write_text(tcl_content)
    logger.info(f"Written TCL script: {tcl_path}")

    # ---- Run Yosys -------------------------------------------------------
    logger.info(f"Running Yosys synthesis for: {top_module}")
    logger.info(f"  RTL file:  {rtl_path}")
    logger.info(f"  Liberty:   {lib_path}")
    logger.info(f"  Netlist:   {netlist_path}")

    result = subprocess.run(
        ["yosys", "-q", "-s", str(tcl_path)],
        capture_output=True,
        text=True,
        cwd=str(WORKSPACE),
    )

    raw_log = result.stdout + result.stderr

    # ---- Parse output ----------------------------------------------------
    cell_count = 0
    area = 0.0
    warnings: List[str] = []
    latches_inferred = 0

    # Number of cells
    m = re.search(r"Number of cells:\s+(\d+)", raw_log)
    if m:
        cell_count = int(m.group(1))

    # Chip area (Yosys reports like "Chip area for module '<top>': <value>")
    m = re.search(r"Chip area for module.*?:\s*([\d.]+)", raw_log)
    if m:
        area = float(m.group(1))

    # Warnings — deduplicate consecutive identical lines
    seen_warnings: set = set()
    for line in raw_log.splitlines():
        if "WARNING:" in line:
            # Strip leading timestamp / context, keep the message after WARNING:
            parts = line.split("WARNING:", 1)
            msg = parts[-1].strip()
            if msg not in seen_warnings:
                seen_warnings.add(msg)
                warnings.append(msg)

    # Latch inferences
    # Yosys prints "Inferred N latches" during synth
    m = re.search(r"Inferred\s+(\d+)\s+latches?", raw_log, re.IGNORECASE)
    if m:
        latches_inferred = int(m.group(1))
    else:
        # Fallback: count lines mentioning "latch" at warning level
        latch_lines = [
            line
            for line in raw_log.splitlines()
            if "latch" in line.lower()
        ]
        latches_inferred = len(latch_lines)

    # ---- Log summary ----------------------------------------------------
    summary_parts = [
        "Synthesis completed" if raw_log else "Synthesis produced no output",
    ]
    if cell_count:
        summary_parts.append(f"Cells: {cell_count}")
    if area:
        summary_parts.append(f"Area: {area}")
    if warnings:
        summary_parts.append(f"Warnings: {len(warnings)}")
    if latches_inferred:
        summary_parts.append(f"Latches: {latches_inferred}")

    logger.info(" — ".join(summary_parts))

    for w in warnings[:5]:
        logger.warning(f"  Synthesis warning: {w}")

    if latches_inferred:
        logger.warning(
            f"Inferred {latches_inferred} latch(es) in design — "
            "check for incomplete case / if statements"
        )

    return {
        "netlist_path": str(netlist_path),
        "area": area,
        "cell_count": cell_count,
        "warnings": warnings,
        "latches_inferred": latches_inferred,
        "log": raw_log,
    }


# ---------------------------------------------------------------------------
# MCP Server
# ---------------------------------------------------------------------------

try:
    from mcp.server import Server
    from mcp.server.stdio import stdio_server
    from mcp.server.models import InitializationOptions

    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False

if MCP_AVAILABLE:

    server = Server("synthesis-server")

    @server.tool()
    async def synthesize(
        rtl_file: str,
        top_module: str,
        liberty_file: str,
    ) -> str:
        """Run Yosys synthesis on the given RTL file.

        Args:
            rtl_file: Path to the Verilog RTL file to synthesize.
            top_module: Name of the top-level module in the RTL.
            liberty_file: Path to the Liberty (.lib) technology library file.

        Returns:
            JSON string containing:
            - netlist_path: path to the synthesized Verilog netlist
            - area: chip area reported by Yosys stat (0 if unavailable)
            - cell_count: number of cells in synthesized design
            - warnings: list of warning messages from Yosys
            - latches_inferred: number of latches inferred during synthesis
            - log: full Yosys output log
        """
        import json

        logger.info("MCP tool 'synthesize' invoked")
        try:
            result = _run_synthesis(
                rtl_file=rtl_file,
                top_module=top_module,
                liberty_file=liberty_file,
            )
            logger.success("Synthesis completed successfully")
            return json.dumps(result, indent=2)
        except Exception as exc:
            logger.error(f"Synthesis failed: {exc}")
            return json.dumps({"error": str(exc)})

    async def main() -> None:
        """Run the MCP server over stdio."""
        async with stdio_server() as (read_stream, write_stream):
            await server.run(
                read_stream,
                write_stream,
                InitializationOptions(
                    server_name="synthesis-server",
                    server_version="0.1.0",
                ),
            )

    if __name__ == "__main__":
        asyncio.run(main())

else:
    # Fallback: expose the plain function when the MCP SDK is not installed.
    # This still imports cleanly so tests and direct calls work.
    logger.warning(
        "MCP Python SDK not installed. "
        "Install with: pip install mcp\n"
        "Falling back to non-MCP mode — use _run_synthesis() directly."
    )

    # When run as __main__ without mcp, show a helpful error.
    if __name__ == "__main__":
        logger.error(
            "Cannot start MCP server: mcp package is not installed.\n"
            "  pip install mcp\n"
            "Then run: python -m v2_verification.mcp_tools.synthesis_server"
        )
