"""
simulation_executor.py — Icarus Verilog simulation runner with real-time log streaming.

A drop-in replacement for v1_core.mcp_tools.simulation_server.run_simulation()
with the same return signature but:

  - Streams each log line via a callback in real-time (for SSE forwarding)
  - Saves generated VCD files to workspace/artifacts
  - Uses line-buffered subprocess.Popen for the underlying make invocation
  - Returns PASS/FAIL from cocotb results.xml

Architecture:
  Cocotb testbenches require the cocotb VPI (Verilog Procedural Interface)
  module loaded into vvp.  The standard cocotb Makefile approach handles
  this, so we generate a minimal Makefile and invoke ``make`` directly.
  The Makefile is the most reliable way to set up the iverilog + VPI
  compilation flags for the local cocotb installation.
"""

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Callable, Optional

from ui.backend.config import settings

logger = __import__("logging").getLogger(__name__)

# Callback invoked with each log line as it is produced.
LogCallback = Callable[[str], None]


def run_simulation(
    rtl_file: str,
    tb_file: str,
    *,
    on_log_line: Optional[LogCallback] = None,
) -> dict:
    """Run Icarus Verilog simulation with a cocotb testbench.

    This function replaces v1_core.mcp_tools.simulation_server.run_simulation()
    and returns the exact same shape::

        {"passed": bool, "log": str}

    Args:
        rtl_file: Absolute path to the Verilog RTL source.
        tb_file:  Absolute path to the cocotb Python testbench module.
        on_log_line: Optional callback — invoked with each output line
                     as the simulation runs (use for real-time SSE streaming).

    Returns:
        {"passed": bool, "log": str}

    Raises:
        FileNotFoundError: if ``rtl_file`` or ``tb_file`` does not exist.
        RuntimeError: if ``cocotb-config`` or ``make`` is not available.
    """
    rtl_path = Path(rtl_file).resolve()
    tb_path = Path(tb_file).resolve()

    if not rtl_path.exists():
        raise FileNotFoundError(f"RTL file not found: {rtl_path}")
    if not tb_path.exists():
        raise FileNotFoundError(f"Testbench file not found: {tb_path}")

    # ---- Detect the toplevel module name --------------------------------
    rtl_source = rtl_path.read_text()
    m = re.search(r"^\s*module\s+(\w+)", rtl_source, re.MULTILINE)
    toplevel = m.group(1) if m else rtl_path.stem
    tb_module = tb_path.stem
    design_name = toplevel

    # ---- Prepare build directory ----------------------------------------
    build_dir = settings.WORKSPACE_DIR / design_name / "sim_build"
    build_dir.mkdir(parents=True, exist_ok=True)

    # Clean stale result / VCD files from previous runs
    results_file = build_dir / "results.xml"
    vcd_file = build_dir / "dump.vcd"
    for f in (results_file, vcd_file):
        if f.exists():
            f.unlink()

    # ---- Locate cocotb makefiles via cocotb-config -----------------------
    try:
        makefiles_dir = (
            subprocess.check_output(["cocotb-config", "--makefiles"])
            .decode()
            .strip()
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        # Fall back to the path inside the current venv
        venv_site = (
            Path(sys.prefix)
            / "lib"
            / f"python{sys.version_info.major}.{sys.version_info.minor}"
            / "site-packages"
            / "cocotb_tools"
            / "makefiles"
        )
        if venv_site.exists():
            makefiles_dir = str(venv_site)
        else:
            raise RuntimeError(
                "Cannot locate cocotb makefiles. "
                "Ensure cocotb is installed and 'cocotb-config --makefiles' works."
            )

    # ---- Write Makefile -------------------------------------------------
    # WAVES=1 generates a Verilog dump shim with $dumpfile / $dumpvars
    # through the cocotb build system (cocotb 2.x API).  The resulting
    # waveform file lives at:
    #   <build_dir>/sim_build/<toplevel>.<fst|vcd>
    makefile_content = (
        "# Auto-generated by rtl2gds-agent simulation_executor\n"
        "SIM = icarus\n"
        "TOPLEVEL_LANG = verilog\n"
        "WAVES = 1\n"
        f"VERILOG_SOURCES = {rtl_path}\n"
        f"TOPLEVEL = {toplevel}\n"
        f"COCOTB_TEST_MODULES = {tb_module}\n"
        "COCOTB_RESULTS_FILE = results.xml\n"
        f"include {makefiles_dir}/Makefile.sim\n"
    )
    makefile_path = build_dir / "Makefile"
    makefile_path.write_text(makefile_content)

    # ---- Set up environment ---------------------------------------------
    env = {
        **os.environ,
        "PYTHONPATH": str(tb_path.parent.resolve()),
        "COCOTB_REDUCED_LOG_FMT": "1",
    }

    # ---- Run make with streaming output ---------------------------------
    log_lines: list[str] = []

    def _capture_and_stream(stream, is_error=False):
        """Read lines from a pipe, accumulate, and invoke the callback."""
        for raw_line in iter(stream.readline, ""):
            line = raw_line.rstrip("\n")
            if not line:
                continue
            log_lines.append(line)
            if on_log_line:
                on_log_line(line)
        stream.close()

    logger.info("Running simulation for %s in %s", toplevel, build_dir)

    process = subprocess.Popen(
        ["make", "-f", str(makefile_path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,  # merge stderr into stdout
        text=True,
        cwd=str(build_dir),
        env=env,
        bufsize=1,  # line-buffered
    )

    _capture_and_stream(process.stdout)

    process.wait()
    exit_code = process.returncode

    # ---- Assemble the full log ------------------------------------------
    raw_log = "\n".join(log_lines)

    # Extract the cocotb-relevant portion (skip make/iverilog compile noise)
    # Cocotb output lines start with a timestamp like "0.00ns" or "     0.00ns"
    cocotb_match = re.search(r"^\s*\d+\.\d+\s*ns", raw_log, re.MULTILINE)
    if cocotb_match:
        log = raw_log[cocotb_match.start():]
    else:
        log = raw_log  # fallback: keep everything

    # Append structured results.xml for the pipeline adapter's existing
    # regex-based test counting (testcase name= ... <failure ...).
    if results_file.exists():
        xml_content = results_file.read_text()
        log += "\n--- results.xml ---\n" + xml_content

    # ---- Determine PASS/FAIL --------------------------------------------
    passed = False
    if results_file.exists():
        content = results_file.read_text()
        passed = "failure" not in content.lower() and "error" not in content.lower()

    # Fallback: if results.xml has no test data, use exit code
    if not results_file.exists():
        passed = exit_code == 0

    # ---- Save waveform (VCD / FST) to a stable location -----------------
    # WAVES=1 via cocotb 2.x generates FST at sim_build/<toplevel>.fst.
    # Fall back to dump.vcd for backward compat.
    waveform_src = None
    waveform_ext = None
    generated_fst = build_dir / "sim_build" / f"{toplevel}.fst"
    if generated_fst.exists():
        waveform_src = generated_fst
        waveform_ext = ".vcd"  # user-facing: always expose as .vcd
    elif vcd_file.exists():
        waveform_src = vcd_file
        waveform_ext = ".vcd"

    if waveform_src is not None:
        dest = settings.WORKSPACE_DIR / design_name / f"{design_name}{waveform_ext}"
        shutil.copy2(str(waveform_src), str(dest))
        log += f"\n--- Waveform saved: {dest} ---\n"
        if on_log_line:
            on_log_line(f"[waveform] {dest}")

    # ---- Final summary --------------------------------------------------
    if passed:
        logger.info("Simulation PASSED for %s", toplevel)
    else:
        logger.warning(
            "Simulation FAILED for %s (exit=%d)", toplevel, exit_code
        )

    if on_log_line:
        on_log_line(f"--- Simulation {'PASSED' if passed else 'FAILED'} ---")

    # Strip control characters that could break SSE JSON
    log = log.replace("[", "(").replace("]", ")")

    return {"passed": passed, "log": log}
